### ISSUE TITLE
PHP nightly!

### ISSUE THREAD

**Issue by dave1010** [Vectorface/dunit#9]
https://github.com/dave1010/php7-docker is a start. Needs some work :-)

**Comment by danbruce** [comment]
Thanks @dave1010. For sure we will add this.

**Comment by danbruce** [comment]
I've added a first version (in dev branch only). See d30a19f6. If you want to try just the image you can do `docker pull vectorface/php-nightly`. The image is inspired by your project but is built off debian:wheezy and then squashed to remove any build deps. Full image size is about 200MB.

**Comment by danbruce** [comment]
Version 2.1 officially supports the PHP 7 github sources. Closing issue.
